
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionEtudiantService", targetNamespace = "http://service/", wsdlLocation = "http://172.20.10.13:8788/GestionEtudiant?wsdl")
public class GestionEtudiantService
    extends Service
{

    private final static URL GESTIONETUDIANTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONETUDIANTSERVICE_EXCEPTION;
    private final static QName GESTIONETUDIANTSERVICE_QNAME = new QName("http://service/", "GestionEtudiantService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.20.10.13:8788/GestionEtudiant?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONETUDIANTSERVICE_WSDL_LOCATION = url;
        GESTIONETUDIANTSERVICE_EXCEPTION = e;
    }

    public GestionEtudiantService() {
        super(__getWsdlLocation(), GESTIONETUDIANTSERVICE_QNAME);
    }

    public GestionEtudiantService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONETUDIANTSERVICE_QNAME, features);
    }

    public GestionEtudiantService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONETUDIANTSERVICE_QNAME);
    }

    public GestionEtudiantService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONETUDIANTSERVICE_QNAME, features);
    }

    public GestionEtudiantService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionEtudiantService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestionEtudiant
     */
    @WebEndpoint(name = "GestionEtudiantPort")
    public GestionEtudiant getGestionEtudiantPort() {
        return super.getPort(new QName("http://service/", "GestionEtudiantPort"), GestionEtudiant.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionEtudiant
     */
    @WebEndpoint(name = "GestionEtudiantPort")
    public GestionEtudiant getGestionEtudiantPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "GestionEtudiantPort"), GestionEtudiant.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONETUDIANTSERVICE_EXCEPTION!= null) {
            throw GESTIONETUDIANTSERVICE_EXCEPTION;
        }
        return GESTIONETUDIANTSERVICE_WSDL_LOCATION;
    }

}
